apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  namespace: pyapp
  labels:
    app: pyapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: gautham1999/gha-pyapp:7a130d7
          ports:
            # this port is used for application 
            - containerPort: 8000
              # this port is used for metric monitoring  
            - containerPort: 9090
