apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
  namespace: pyapp
  labels:
    app: pyapp
spec:
  selector:
    app: pyapp
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
