name: multiple job workflow
on: workflow_dispatch
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: build stage
        run: echo "this is build step"
   test:
      run-on: ubuntu-latest 
      needs: build
      steps:
        - name: test stage 
          run: echo "this is test step"
   deploy:
      run-on: ubuntu-latest
      steps:
        - name: deploy stage
          run: echo "this is deploy step"
